language: node_js
node_js:
  - 17
env:
  - DB_URI='mongodb+srv://thomasho:codesmith@cluster0.xnki76n.mongodb.net/?retryWrites=true&w=majority' PORT=3000
install:
  - npm install
script:
  - npm run test